"""crear tablas iniciales

Revision ID: 64e1f00aecba
Revises: 
Create Date: 2026-03-17 10:38:07.777268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e1f00aecba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=100), nullable=True),
    sa.Column('email_cliente', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('total_cents', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio_cents', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('tallas', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('enviada', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_id'), 'alertas', ['id'], unique=False)
    op.create_table('lineas_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_unidad_cents', sa.Integer(), nullable=True),
    sa.Column('talla', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineas_pedido_id'), 'lineas_pedido', ['id'], unique=False)
    op.create_table('solicitudes_factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('email_cliente', sa.String(length=100), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('procesada', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_factura_id'), 'solicitudes_factura', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitudes_factura_id'), table_name='solicitudes_factura')
    op.drop_table('solicitudes_factura')
    op.drop_index(op.f('ix_lineas_pedido_id'), table_name='lineas_pedido')
    op.drop_table('lineas_pedido')
    op.drop_index(op.f('ix_alertas_id'), table_name='alertas')
    op.drop_table('alertas')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    # ### end Alembic commands ###
